[package]
name = "ihex_ext"
version = "1.0.0"
edition = "2021"
license = "MIT OR Apache-2.0"
description = "A crate adding convenience methods for `ihex`"
repository = "https://github.com/yodaldevoid/ihex_binary"

[dependencies]
ihex = "3.0.0"
log = "0.4.0"
thiserror = "1.0.2"
